### PR TITLE
add latest message model to properly deserialize groups

### PR DESCRIPTION
**Pull request by dylanrb123**
The JSON for a latest message is not at all the same as a regular message. I went with a new model instead of changing the existing one because that has usage elsewhere so I didn't want to overload the model and this is quite different. 

@szabowexler

### CODE REVIEW

**Comment by dylanrb123** [comment]
@szabowexler mind taking a look at this when you have a chance? Just realized it never got merged

**Comment by darcatron** [comment]
@dylanrb123 have you guys been using these changes at all? I see no problem in merging this in, but it'd be nice to have some extra validation that it's been working for you guys in more realistic use cases

**Comment by dylanrb123** [comment]
No we aren't using it, I was just fixing a bug that someone else reported.

**Comment by szabowexler** [comment]
Sorry, totally missed this. I'm in next week and can take a look then. I'm
also planning on cutting a release, so we can merge and deal with all
outstanding PRs then.

**Comment by darcatron** [comment]
This is stale so I'm going to close this out. If anyone wants to revisit it, the code will be accessible

**Pull request closed without merging**
